vouch:
  port: 9090
  document_root: /vouch
  allowAllUsers: true
  cookie:
    domain: ${VOUCH_COOKIE_DOMAIN}
    secure: false
    name: VouchCookie
    maxAge: 4320
  jwt:
    secret: ${VOUCH_JWT_SECRET}
    maxAge: 4320

oauth:
  provider: google
  client_id: ${VOUCH_GOOGLE_CLIENT_ID}
  client_secret: ${VOUCH_GOOGLE_CLIENT_SECRET}
  callback_url: ${VOUCH_CALLBACK_URL}
  scopes:
    - openid
    - email
    - profile
