#!/usr/bin/env tsx
/**
 * Code-gen using-git and using-gh skills from the allowlist sets exported
 * by policy-git.ts and policy-gh.ts. Structured-command narrative is
 * hardcoded in this script (8 commands — keeping it data-driven here is
 * less code than building a registry in the source modules).
 *
 * The allow/deny surface *is* data-driven: passthrough command lists come
 * straight from the exported Sets, so adding a subcommand to the policy
 * automatically updates the skill on the next `pnpm gen:skills`.
 *
 * Usage:
 *   pnpm gen:skills        write skill files
 *   pnpm gen:skills:check  fail if skills are stale
 */

import { mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";

import {
  ALLOWED_GIT_SUBCOMMANDS,
  NO_PAGER_SAFE_GIT_SUBCOMMANDS,
} from "../packages/remote-cli/src/policy-git.js";
import { ALLOWED_GH_COMMANDS } from "../packages/remote-cli/src/policy-gh.js";

const __dirname = dirname(fileURLToPath(import.meta.url));
const REPO_ROOT = resolve(__dirname, "..");
const SKILL_ROOT = join(REPO_ROOT, "docker/opencode/config/skills");

const GENERATED_NOTICE = "<!-- Generated by scripts/gen-policy-skill.ts. Do not edit. -->";

// Structured-command narrative. One entry per command with bespoke flag
// validation in policy-git.ts / policy-gh.ts. The flag tables below mirror
// the validator's allowlist — if they drift, policy.test.ts starts failing
// because the skill's claim won't match runtime enforcement.
const GIT_STRUCTURED = [
  {
    name: "push",
    narrative:
      "Only pushes to `origin`. Flags: `-u`/`--set-upstream`, `--no-verify`, `--dry-run`/`-n`, `--verbose`/`-v`, `--quiet`/`-q`. Refspecs cannot target protected branches (`main`, `master`) or force-update via leading `+`. Implicit `git push` works when the current branch has a safe `origin` upstream — the server rewrites it to `HEAD:refs/heads/<branch>` before exec.",
  },
  {
    name: "config",
    narrative:
      "Read-only lookups only: `--get`, `--get-all`, `--get-regexp`, optionally with `--show-origin`. Requires a key or pattern.",
  },
  {
    name: "check-ignore",
    narrative:
      "Direct path lookups only. Flags: `-q`/`--quiet`, `-v`/`--verbose`, `-n`/`--non-matching`. At least one path required.",
  },
  {
    name: "symbolic-ref",
    narrative:
      "Read-only: exactly one ref argument. Flags: `--short`, `-q`/`--quiet`. Mutation forms are denied.",
  },
  {
    name: "worktree",
    narrative:
      "`git worktree add <path>` requires the path to start with `/workspace/worktrees/`. Other sub-subcommands (list, remove, prune, move, lock, unlock, repair) pass through.",
  },
  {
    name: "remote",
    narrative:
      "Read-only sub-subcommands only: `show`, `get-url`, `-v`/`--verbose`. `add`, `remove`, `set-url`, `rename` are denied.",
  },
  {
    name: "checkout",
    narrative:
      "Only the restore form: `git checkout [<ref>] -- <paths>` (or `git checkout <pathspec>` for common file extensions). Branch switching is denied — use `git worktree add` instead.",
  },
];

const GH_STRUCTURED = [
  {
    name: "pr create",
    narrative:
      "Required: `--title`/`-t`, `--body`/`-b`. Optional: `--base`/`-B`, `--head`/`-H` (must be a branch in the current repo), `--draft`. Blocked: `--editor`, `--web`, `--body-file`, `--repo`/`-R`.",
  },
  {
    name: "pr comment",
    narrative:
      "Required: `--body`/`-b`. Optional positional selector: numeric PR number, current-repo PR URL, or branch name. Blocked: `--edit-last`, `--delete-last`, `--create-if-none`, `--yes`, `--editor`, `--web`, `--body-file`, `--repo`/`-R`.",
  },
  {
    name: "issue comment",
    narrative:
      "Required: `--body`/`-b` and exactly one positional selector (numeric issue number or current-repo issue URL). Blocked: same mutation/interactive/file/cross-repo flags as `pr comment`.",
  },
  {
    name: "pr review",
    narrative:
      "Required: `--body`/`-b` and exactly one of `--comment`/`-c` or `--request-changes`/`-r`. Optional positional PR selector. `--approve`/`-a` is **denied** — PR approval is a human gate. Blocked: `--editor`, `--web`, `--body-file`, `--repo`/`-R`.",
  },
];

function usingGitSkill(): string {
  const strictNames = new Set(GIT_STRUCTURED.map((s) => s.name));
  const passthrough = [...ALLOWED_GIT_SUBCOMMANDS].filter((name) => !strictNames.has(name)).sort();
  const noPagerSafe = [...NO_PAGER_SAFE_GIT_SUBCOMMANDS].sort();

  return `---
name: using-git
description: Git command surface allowed by Thor's remote-cli server policy. Thor's git is append-only to the local repo and to origin. Load this skill to see what commands are allowed and the common redirect patterns.
---

${GENERATED_NOTICE}

## Posture

All \`git\` commands go through Thor's remote-cli which enforces:

- **No branch switching in-place.** \`git checkout <ref>\` and \`git switch\` are denied — use \`git worktree add <path> <ref>\` instead.
- **No force-push.** \`--force\` and \`--force-with-lease\` on \`git push\` are denied.
- **Pushes only to \`origin\`**, never to protected branches \`main\` or \`master\`.
- **Read-only \`git config\`, \`git remote\`, \`git symbolic-ref\`** — no mutation.
- **\`git checkout -- <path>\`** (restore from index/HEAD) is allowed.

## Common redirects

Instead of switching branches in place:
\`\`\`
git worktree add /workspace/worktrees/<repo>/<branch> <ref>
\`\`\`

Instead of \`gh pr checkout 123\`:
\`\`\`
git fetch origin pull/123/head:pr-123
git worktree add /workspace/worktrees/<repo>/pr-123 pr-123
\`\`\`

## Structured commands

${GIT_STRUCTURED.map((s) => `### \`git ${s.name}\`\n\n${s.narrative}`).join("\n\n")}

## Passthrough subcommands (any arguments accepted)

${passthrough.map((n) => `- \`git ${n}\``).join("\n")}

## Safe under \`git --no-pager\`

${noPagerSafe.map((n) => `- \`git ${n}\``).join("\n")}
`;
}

function usingGhSkill(): string {
  const strictKeys = new Set(GH_STRUCTURED.map((s) => s.name));
  const passthrough = [...ALLOWED_GH_COMMANDS].filter((k) => !strictKeys.has(k)).sort();

  return `---
name: using-gh
description: GitHub CLI surface allowed by Thor's remote-cli server policy. Append-only: Thor can create PRs, comments, and non-approval reviews but cannot approve, merge, edit, or delete prior artifacts.
---

${GENERATED_NOTICE}

## Posture

All \`gh\` commands go through Thor's remote-cli which enforces:

- **Append-only writes.** Create PRs, post comments, submit \`--comment\`/\`--request-changes\` reviews. Never approve, merge, edit, or delete.
- **Current-repo only.** Write commands cannot target another repository — \`--repo\`/\`-R\` is blocked on PR/comment/review writes.
- **\`gh api\` is blocked.** Use typed \`gh pr\`/\`gh issue\`/\`gh repo\`/etc. subcommands.
- **PR approval is a human gate.** \`gh pr review --approve\` is denied.

## Common redirect

Instead of \`gh pr checkout <N>\`:
\`\`\`
git fetch origin pull/<N>/head:pr-<N>
git worktree add /workspace/worktrees/<repo>/pr-<N> pr-<N>
\`\`\`

## Structured commands

${GH_STRUCTURED.map((s) => `### \`gh ${s.name}\`\n\n${s.narrative}`).join("\n\n")}

## Read-only (passthrough) commands

${passthrough.map((k) => `- \`gh ${k}\``).join("\n")}
`;
}

function writeSkill(name: string, content: string): void {
  const dir = join(SKILL_ROOT, name);
  mkdirSync(dir, { recursive: true });
  writeFileSync(join(dir, "SKILL.md"), content);
}

function checkSkill(name: string, expected: string): boolean {
  const path = join(SKILL_ROOT, name, "SKILL.md");
  try {
    return readFileSync(path, "utf8") === expected;
  } catch {
    return false;
  }
}

function main(): void {
  const check = process.argv.includes("--check");
  const git = usingGitSkill();
  const gh = usingGhSkill();

  if (check) {
    const gitOk = checkSkill("using-git", git);
    const ghOk = checkSkill("using-gh", gh);
    if (gitOk && ghOk) {
      console.log("skills are in sync with policy");
      return;
    }
    if (!gitOk) console.error("using-git/SKILL.md is stale — run `pnpm gen:skills`");
    if (!ghOk) console.error("using-gh/SKILL.md is stale — run `pnpm gen:skills`");
    process.exit(1);
  }

  writeSkill("using-git", git);
  writeSkill("using-gh", gh);
  console.log("wrote using-git and using-gh skills");
}

main();
