#!/usr/bin/env tsx
/**
 * Code-gen using-git and using-gh skills from the allowlist sets exported
 * by policy-git.ts and policy-gh.ts. Structured-command narrative is
 * hardcoded in this script (8 commands — keeping it data-driven here is
 * less code than building a registry in the source modules).
 *
 * The allow/deny surface *is* data-driven: passthrough command lists come
 * straight from the exported Sets, so adding a subcommand to the policy
 * automatically updates the skill on the next `pnpm gen:skills`.
 *
 * Usage:
 *   pnpm gen:skills        write skill files
 *   pnpm gen:skills:check  fail if skills are stale
 */

import { mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";

import {
  ALLOWED_GIT_SUBCOMMANDS,
  NO_PAGER_SAFE_GIT_SUBCOMMANDS,
} from "../packages/remote-cli/src/policy-git.js";
import { ALLOWED_GH_COMMANDS } from "../packages/remote-cli/src/policy-gh.js";

const __dirname = dirname(fileURLToPath(import.meta.url));
const REPO_ROOT = resolve(__dirname, "..");
const SKILL_ROOT = join(REPO_ROOT, "docker/opencode/config/skills");

const GENERATED_NOTICE = "<!-- Generated by scripts/gen-policy-skill.ts. Do not edit. -->";

// Structured-command narrative. One entry per command with bespoke flag
// validation in policy-git.ts / policy-gh.ts. The flag tables below mirror
// the validator's allowlist — if they drift, policy.test.ts starts failing
// because the skill's claim won't match runtime enforcement.
const GIT_STRUCTURED = [
  {
    name: "merge-base",
    narrative: "Exact shape only: `git merge-base <left> <right>`.",
  },
  {
    name: "branch",
    narrative:
      "Read-only only: `git branch --show-current`, `git branch -a`, or `git branch --all`.",
  },
  {
    name: "remote",
    narrative:
      "Read-only only: `git remote`, `git remote -v`, `git remote --verbose`, `git remote show origin`, `git remote get-url origin`.",
  },
  {
    name: "fetch",
    narrative:
      "Exact remote only: `git fetch origin [<ref>...]`. Flags are not part of the supported surface.",
  },
  {
    name: "restore",
    narrative:
      "Use `git restore [--source <tree>] -- <path...>` for file restore. This replaces all `git checkout` restore support.",
  },
  {
    name: "add",
    narrative: "Allowed forms: `git add -A` or `git add <path...>`. Extra flags are not supported.",
  },
  {
    name: "commit",
    narrative: "Exact non-interactive shape only: `git commit -m <message>`.",
  },
  {
    name: "worktree",
    narrative:
      "Only `git worktree add -b <branch> <path> [<start-point>]` is supported, and `<path>` must stay under `/workspace/worktrees/`.",
  },
  {
    name: "push",
    narrative:
      "Only `git push [--dry-run] [-u|--set-upstream] origin HEAD:refs/heads/<branch>` is supported. Force, implicit upstream resolution, and pushes to protected branches (`main`, `master`) are denied.",
  },
];

const GH_STRUCTURED = [
  {
    name: "pr create",
    narrative:
      "Required: `--title`/`-t`, `--body`/`-b`. Optional: `--base`/`-B`, `--draft`. Blocked: `--head`, `--editor`, `--web`, `--body-file`, and `--repo`/`-R`.",
  },
  {
    name: "pr comment",
    narrative:
      "Required: numeric PR selector plus `--body`/`-b`. Blocked: non-numeric selectors, edit/delete modes, interactive/file flags, and `--repo`/`-R`.",
  },
  {
    name: "issue comment",
    narrative:
      "Required: numeric issue selector plus `--body`/`-b`. Blocked: non-numeric selectors, interactive/file flags, and `--repo`/`-R`.",
  },
  {
    name: "pr review",
    narrative:
      "Required: `--body`/`-b` and exactly one of `--comment`/`-c` or `--request-changes`/`-r`. Optional positional selector: numeric PR number only. `--approve`/`-a` is denied. Blocked: non-numeric selectors, interactive/file flags, and `--repo`/`-R`.",
  },
  {
    name: "api",
    narrative:
      "Implicit GET only. Required: REST endpoint as the first positional argument. Optional output flags: `--jq`/`-q`, `--template`/`-t`, `--silent`, `--include`/`-i`. Blocked: `graphql`, `--method`/`-X`, `--input`, `-H`/`--header`, `--preview`, `--hostname`, `-f`/`--raw-field`, and `-F`/`--field`.",
  },
];

function usingGitSkill(): string {
  const strictNames = new Set(GIT_STRUCTURED.map((s) => s.name));
  const passthrough = [...ALLOWED_GIT_SUBCOMMANDS].filter((name) => !strictNames.has(name)).sort();
  const noPagerSafe = [...NO_PAGER_SAFE_GIT_SUBCOMMANDS].sort();
  const noPagerSection =
    noPagerSafe.length > 0
      ? noPagerSafe.map((n) => `- \`git ${n}\``).join("\n")
      : "No `git --no-pager` forms are supported.";

  return `---
name: using-git
description: Git command surface allowed by Thor's remote-cli server policy. Thor's git is append-only to the local repo and to origin. Load this skill to see what commands are allowed and the common redirect patterns.
---

${GENERATED_NOTICE}

## Posture

All \`git\` commands go through Thor's remote-cli which enforces:

- **No branch switching in-place.** \`git checkout <ref>\` and \`git switch\` are denied — use \`git worktree add <path> <ref>\` instead.
- **No force-push or implicit push resolution.** Pushes must target \`origin HEAD:refs/heads/<branch>\` explicitly.
- **Pushes only to \`origin\`**, never to protected branches \`main\` or \`master\`.
- **No config or ref-introspection helpers outside the allowlist.** \`git config\`, \`git symbolic-ref\`, and \`git check-ignore\` are denied.
- **Use \`git restore\` for file restore.** \`git checkout -- <path>\` is not part of the supported surface.

## Common redirects

Instead of switching branches in place:
\`\`\`
git worktree add -b <branch> /workspace/worktrees/<repo>/<branch> <start-point>
\`\`\`

Instead of \`gh pr checkout 123\`:
\`\`\`
git fetch origin pull/123/head:pr-123
git worktree add -b pr-123 /workspace/worktrees/<repo>/pr-123 pr-123
\`\`\`

## Structured commands

${GIT_STRUCTURED.map((s) => `### \`git ${s.name}\`\n\n${s.narrative}`).join("\n\n")}

## Passthrough subcommands (any arguments accepted)

${passthrough.map((n) => `- \`git ${n}\``).join("\n")}

## Safe under \`git --no-pager\`

${noPagerSection}
`;
}

function usingGhSkill(): string {
  const strictKeys = new Set(GH_STRUCTURED.map((s) => s.name));
  const passthrough = [...ALLOWED_GH_COMMANDS].filter((k) => !strictKeys.has(k)).sort();

  return `---
name: using-gh
description: GitHub CLI surface allowed by Thor's remote-cli server policy. Append-only: Thor can create PRs, comments, and non-approval reviews but cannot approve, merge, edit, or delete prior artifacts.
---

${GENERATED_NOTICE}

## Posture

All \`gh\` commands go through Thor's remote-cli which enforces:

- **Append-only writes.** Create PRs, post comments, submit \`--comment\`/\`--request-changes\` reviews. Never approve, merge, edit, or delete.
- **Repo-targeting flags are blocked.** \`--repo\`/\`-R\` is not part of the supported surface.
- **\`gh api\` is a tiny read-only subset.** REST only, implicit GET only, output-shaping flags only.
- **PR approval is a human gate.** \`gh pr review --approve\` is denied.

## Common redirect

Instead of \`gh pr checkout <N>\`:
\`\`\`
git fetch origin pull/<N>/head:pr-<N>
git worktree add -b pr-<N> /workspace/worktrees/<repo>/pr-<N> pr-<N>
\`\`\`

## Structured commands

${GH_STRUCTURED.map((s) => `### \`gh ${s.name}\`\n\n${s.narrative}`).join("\n\n")}

## Read-only (passthrough) commands

${passthrough.map((k) => `- \`gh ${k}\``).join("\n")}
`;
}

function writeSkill(name: string, content: string): void {
  const dir = join(SKILL_ROOT, name);
  mkdirSync(dir, { recursive: true });
  writeFileSync(join(dir, "SKILL.md"), content);
}

function checkSkill(name: string, expected: string): boolean {
  const path = join(SKILL_ROOT, name, "SKILL.md");
  try {
    return readFileSync(path, "utf8") === expected;
  } catch {
    return false;
  }
}

function main(): void {
  const check = process.argv.includes("--check");
  const git = usingGitSkill();
  const gh = usingGhSkill();

  if (check) {
    const gitOk = checkSkill("using-git", git);
    const ghOk = checkSkill("using-gh", gh);
    if (gitOk && ghOk) {
      console.log("skills are in sync with policy");
      return;
    }
    if (!gitOk) console.error("using-git/SKILL.md is stale — run `pnpm gen:skills`");
    if (!ghOk) console.error("using-gh/SKILL.md is stale — run `pnpm gen:skills`");
    process.exit(1);
  }

  writeSkill("using-git", git);
  writeSkill("using-gh", gh);
  console.log("wrote using-git and using-gh skills");
}

main();
