#!/usr/bin/env tsx
/**
 * Code-gen using-git and using-gh skills from the command spec tables.
 *
 * The specs are the single source of truth for runtime enforcement. This
 * script projects them into markdown skills so opencode learns the allowed
 * surface from the same data that gates its commands. Drift is impossible
 * by construction.
 *
 * Usage:
 *   tsx scripts/gen-policy-skill.ts          # write skill files
 *   tsx scripts/gen-policy-skill.ts --check  # fail if skills are stale
 */

import { mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";

import { GIT_SPECS } from "../packages/remote-cli/src/policy-git.js";
import { GH_SPECS } from "../packages/remote-cli/src/policy-gh.js";
import type { CommandSpec } from "../packages/remote-cli/src/policy-spec.js";

const __dirname = dirname(fileURLToPath(import.meta.url));
const REPO_ROOT = resolve(__dirname, "..");
const SKILL_ROOT = join(REPO_ROOT, "docker/opencode/config/skills");

const GENERATED_NOTICE =
  "<!-- Generated by scripts/gen-policy-skill.ts from policy-git.ts / policy-gh.ts. Do not edit. -->";

function usingGitSkill(): string {
  const passthroughNames = GIT_SPECS.filter((s) => s.passthrough).map((s) => s.path[0]);
  const structured = GIT_SPECS.filter((s) => !s.passthrough);

  return `---
name: using-git
description: Git command surface allowed by Thor's remote-cli server policy. Thor's git is append-only to the local repo and to origin. Load this skill to see what commands are allowed and the common redirect patterns.
---

${GENERATED_NOTICE}

## Posture

All \`git\` commands go through Thor's remote-cli which enforces:

- **No branch switching in-place.** \`git checkout <ref>\` and \`git switch\` are denied — use \`git worktree add <path> <ref>\` instead.
- **No force-push.** \`--force\` and \`--force-with-lease\` on \`git push\` are denied.
- **Pushes only to \`origin\`**, never to protected branches \`main\` or \`master\`.
- **Read-only \`git config\`, \`git remote\`, \`git symbolic-ref\`** — no mutation.
- **\`git checkout -- <path>\`** (restore from index/HEAD) is allowed.

## Common redirects

Instead of switching branches in place:
\`\`\`
git worktree add /workspace/worktrees/<repo>/<branch> <ref>
\`\`\`

Instead of \`gh pr checkout 123\`:
\`\`\`
git fetch origin pull/123/head:pr-123
git worktree add /workspace/worktrees/<repo>/pr-123 pr-123
\`\`\`

Implicit \`git push\` works when the current branch has a safe \`origin\` upstream — the server rewrites it to an explicit \`HEAD:refs/heads/<branch>\`.

## Caveats on passthrough subcommands

- \`git worktree add <path>\` — the path must be under \`/workspace/worktrees/\`.
- \`git remote\` — only read-only sub-subcommands (\`show\`, \`get-url\`, \`-v\`). No \`add\`/\`remove\`/\`set-url\`.

## Allowed subcommands

Passthrough (any arguments accepted, see caveats above):

${passthroughNames.map((n) => `- \`git ${n}\``).join("\n")}

Structured (specific flags only):

${structured.map(renderStructuredSection).join("\n\n")}
`;
}

function usingGhSkill(): string {
  const passthrough = GH_SPECS.filter((s) => s.passthrough);
  const structured = GH_SPECS.filter((s) => !s.passthrough);

  return `---
name: using-gh
description: GitHub CLI surface allowed by Thor's remote-cli server policy. Append-only: Thor can create PRs, comments, and non-approval reviews but cannot approve, merge, edit, or delete prior artifacts.
---

${GENERATED_NOTICE}

## Posture

All \`gh\` commands go through Thor's remote-cli which enforces:

- **Append-only writes.** Create PRs, post comments, submit \`--comment\`/\`--request-changes\` reviews. Never approve, merge, edit, or delete.
- **Current-repo only.** Write commands cannot target another repository — \`--repo\`/\`-R\` is blocked on PR/comment/review writes.
- **\`gh api\` is blocked.** Use typed \`gh pr\`/\`gh issue\`/\`gh repo\`/etc. subcommands.
- **PR approval is a human gate.** \`gh pr review --approve\` is denied.

## Common redirect

Instead of \`gh pr checkout <N>\`:
\`\`\`
git fetch origin pull/<N>/head:pr-<N>
git worktree add /workspace/worktrees/<repo>/pr-<N> pr-<N>
\`\`\`

## Allowed commands

Read-only (passthrough):

${passthrough.map((s) => `- \`gh ${s.path.join(" ")}\``).join("\n")}

Write (structured, append-only):

${structured.map(renderStructuredSection).join("\n\n")}
`;
}

function renderStructuredSection(spec: CommandSpec): string {
  const title = spec.path.join(" ");
  const parts: string[] = [`### \`${title}\``];

  const required = spec.requiredFlags ?? [];
  const flagEntries = Object.entries(spec.flags ?? {});

  if (flagEntries.length > 0) {
    const rows: string[] = [];
    for (const [name, flagSpec] of flagEntries) {
      const kind = flagSpec.kind === "bool" ? "switch" : "value";
      const aliases = aliasesFor(spec, name);
      const req = required.includes(name) ? " **required**" : "";
      const aliasNote =
        aliases.length > 0 ? ` (aliases: ${aliases.map((a) => `\`${a}\``).join(", ")})` : "";
      rows.push(`- \`${name}\` ${kind}${aliasNote}${req}`);
    }
    parts.push(`Flags:\n${rows.join("\n")}`);
  }

  if (spec.requireOneOf) {
    parts.push(`Exactly one of: ${spec.requireOneOf.flags.map((f) => `\`${f}\``).join(" / ")}`);
  }

  if (spec.positional) {
    const { min, max } = spec.positional;
    if (max === 0) {
      parts.push("No positional arguments.");
    } else {
      let range: string;
      if (min === max) range = `exactly ${min}`;
      else if (max >= 1000) range = `${min}+`;
      else range = `${min}–${max}`;
      parts.push(`Positional: ${range}`);
    }
  }

  return parts.join("\n\n");
}

function aliasesFor(spec: CommandSpec, canonical: string): string[] {
  if (!spec.aliases) return [];
  return Object.entries(spec.aliases)
    .filter(([, c]) => c === canonical)
    .map(([alias]) => alias);
}

function writeSkill(name: string, content: string): void {
  const dir = join(SKILL_ROOT, name);
  mkdirSync(dir, { recursive: true });
  writeFileSync(join(dir, "SKILL.md"), content);
}

function checkSkill(name: string, expected: string): boolean {
  const path = join(SKILL_ROOT, name, "SKILL.md");
  try {
    const actual = readFileSync(path, "utf8");
    return actual === expected;
  } catch {
    return false;
  }
}

function main(): void {
  const check = process.argv.includes("--check");
  const git = usingGitSkill();
  const gh = usingGhSkill();

  if (check) {
    const gitOk = checkSkill("using-git", git);
    const ghOk = checkSkill("using-gh", gh);
    if (gitOk && ghOk) {
      console.log("skills are in sync with policy specs");
      return;
    }
    if (!gitOk)
      console.error("using-git/SKILL.md is stale — run `tsx scripts/gen-policy-skill.ts`");
    if (!ghOk) console.error("using-gh/SKILL.md is stale — run `tsx scripts/gen-policy-skill.ts`");
    process.exit(1);
  }

  writeSkill("using-git", git);
  writeSkill("using-gh", gh);
  console.log("wrote using-git and using-gh skills");
}

main();
